import type { CharacterDef } from "@/lib/types";

// Starter roster. To add a fighter, define another CharacterDef here —
// the engine, renderer and select screen are fully data-driven.
export const STARTER_CHARACTERS: CharacterDef[] = [
  {
    id: "trump",
    name: "Donald Trump",
    tagline: "The Final Boss Tan",
    // Boss-tier: roughly 2x the baseline of the rest of the roster.
    stats: { hp: 240, speed: 1.0, power: 2.3 },
    special: {
      type: "projectile",
      name: "MAGA EAGLE",
      taunt: "MAGA! Get 'em, boy!",
      power: 1.3,
      visual: "eagle",
    },
    look: {
      skin: "#f0a05a",
      hair: "#f7dd8a",
      suit: "#1a1a2e",
      tie: "#d31f2b",
      accent: "#d31f2b",
      hairStyle: "swoop",
      accessory: "cap",
      build: "wide",
      nose: "bulb",
    },
    intro: "This fight will be HUGE.",
    win: "Tremendous victory. The best win, ever!",
  },
  {
    id: "biden",
    name: "Joe Biden",
    tagline: "Ice Cream Enjoyer",
    stats: { hp: 130, speed: 0.9, power: 1.0 },
    special: {
      type: "nap",
      name: "SLEEPY JOE",
      taunt: "Just a little power nap... huh? What was I doing?",
      power: 1.0,
    },
    look: {
      skin: "#f2c9a0",
      hair: "#f4f4f4",
      suit: "#14213d",
      tie: "#3d5a80",
      accent: "#90e0ef",
      hairStyle: "fluff",
      accessory: "aviators",
      build: "slim",
      nose: "broad",
    },
    intro: "C'mon, man! Let's do this thing.",
    win: "That's a big... uh... win. Jack!",
  },
  {
    id: "harris",
    name: "Kamala Harris",
    tagline: "Coconut Tree Climber",
    stats: { hp: 100, speed: 1.4, power: 0.95 },
    special: {
      type: "vanish",
      name: "IDENTITY SHIFT",
      taunt: "Which version of me are you fighting?",
      power: 1.1,
    },
    look: {
      skin: "#c98b5e",
      hair: "#2b1a10",
      suit: "#3a3a44",
      tie: "#e0e0e0",
      accent: "#f2a65a",
      hairStyle: "bun",
      accessory: "pearls",
      build: "slim",
      nose: "button",
    },
    intro: "Let's fight with joy!",
    win: "I was told there would be coconuts.",
  },
  {
    id: "obama",
    name: "Barack Obama",
    tagline: "The Cool One",
    stats: { hp: 105, speed: 1.25, power: 1.1 },
    special: {
      type: "shockwave",
      name: "OBAMACARE",
      taunt: "OBAMACARE! Everyone's covered!",
      power: 1.2,
    },
    look: {
      skin: "#9c6b43",
      hair: "#101010",
      suit: "#4a4e57",
      tie: "#2a9d8f",
      accent: "#2a9d8f",
      hairStyle: "wave",
      accessory: "flagpin",
      build: "slim",
      nose: "broad",
    },
    intro: "OBAMACARE! Yes we can... throw hands.",
    win: "There is no red state or blue state. Only wins.",
  },
  {
    id: "bernie",
    name: "Bernie Sanders",
    tagline: "Once Again Asking",
    stats: { hp: 110, speed: 1.05, power: 1.15 },
    special: {
      type: "shockwave",
      name: "MILLIONAIRES AND",
      taunt: "I am once again asking for your health bar!",
      power: 1.15,
    },
    look: {
      skin: "#e8c39e",
      hair: "#e8e8e8",
      suit: "#2f3a4a",
      tie: "#6d8ea0",
      accent: "#8ecae6",
      hairStyle: "fluff",
      accessory: "glasses",
      build: "normal",
      nose: "hook",
    },
    intro: "I am once again asking you to step outside.",
    win: "Not me. Us. Mostly me, though.",
  },
  {
    id: "hillary",
    name: "Hillary Clinton",
    tagline: "The Email Archive",
    stats: { hp: 108, speed: 1.15, power: 1.1 },
    special: {
      type: "counter",
      name: "DELETED EMAILS",
      taunt: "I have no recollection of that punch.",
      power: 1.2,
    },
    look: {
      skin: "#f0cdae",
      hair: "#e3c56a",
      suit: "#7b3fa0",
      tie: "#f5f0e6",
      accent: "#b388ff",
      hairStyle: "short",
      accessory: "pearls",
      build: "normal",
      nose: "button",
    },
    intro: "I've prepared for this. Extensively.",
    win: "That one's going in the archive.",
  },
  {
    id: "elon",
    name: "Elon Tusk",
    tagline: "Ships The Patch Live",
    stats: { hp: 102, speed: 1.3, power: 1.15 },
    special: {
      type: "dash",
      name: "HYPERLOOP",
      taunt: "This is technically a tunnel. Trust me.",
      power: 1.25,
    },
    look: {
      skin: "#eec6a6",
      hair: "#3a2a20",
      suit: "#1b1b1b",
      tie: "#4cc9f0",
      accent: "#4cc9f0",
      hairStyle: "pomp",
      accessory: "none",
      build: "normal",
      nose: "broad",
    },
    intro: "Deploying to production. Live.",
    win: "Ship it. We'll patch the bruises later.",
  },
  {
    id: "tangjie",
    name: "Tang Jie",
    tagline: "God-Tier Legend",
    // God-tier: overwhelmingly stronger than even boss-tier Trump.
    // Starters bypass the custom-character validator, so these values are
    // intentionally far beyond the 120/1.6/1.4 custom caps.
    stats: { hp: 999, speed: 1.9, power: 5.0 },
    special: {
      type: "barrage",
      name: "TANG QUAKE",
      taunt: "The legend shakes the earth itself!",
      power: 3.0,
    },
    look: {
      skin: "#f0c8a0",
      hair: "#1a1a1a",
      suit: "#b91c1c",
      tie: "#facc15",
      accent: "#facc15",
      hairStyle: "spiky",
      accessory: "glasses",
      build: "normal",
      nose: "button",
    },
    intro: "The legend has descended.",
    win: "As expected. GG.",
  },
];

export const STARTERS_BY_ID: Record<string, CharacterDef> = Object.fromEntries(
  STARTER_CHARACTERS.map((c) => [c.id, c])
);
